### ISSUE TITLE
Lock files while downloading assets

### ISSUE THREAD

**Issue by nutrik** [dionhaefner/veros#57] opened 2019-05-31 11:05 UTC
I am trying to run global_flexible setup from Veros' setup gallery. 

**Run script:**

```
#!/bin/bash -l
# 
#SBATCH -p aegir
#SBATCH -A ocean
#SBATCH --job-name=flexdeg
#SBATCH --time=23:59:59
#SBATCH --constraint=v1
#SBATCH --nodes=2
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --exclusive
##SBATCH --mail-type=ALL
##SBATCH --mail-user=<REDACTED>
##SBATCH --output=slurm.out

export OMP_NUM_THREADS=1
module load veros/23052019

srun -v --mpi=pmi2 --kill-on-bad-exit python -m mpi4py global_flexible.py -n 8 4 -b bohrium >& veros_run.log
```

and getting md5 sum mismatch of forcing & bathymetry files

**Veros log file:**
```
srun: defined options for program `srun'
srun: --------------- ---------------------
srun: user           : `nutrik'
srun: uid            : 16001
srun: gid            : 16000
srun: cwd            : /lustre/hpc/ocean/nutrik/veros_cases/global_flexible
srun: ntasks         : 32 (set)
srun: cpus_per_task  : 1
srun: nodes          : 2 (set)
srun: jobid          : 13466356 (default)
srun: partition      : default
srun: profile        : `NotSet'
srun: job name       : `2deg'
srun: reservation    : `(null)'
srun: burst_buffer   : `(null)'
srun: wckey          : `(null)'
srun: cpu_freq_min   : 4294967294
srun: cpu_freq_max   : 4294967294
srun: cpu_freq_gov   : 4294967294
srun: switches       : -1
srun: wait-for-switches : -1
srun: distribution   : unknown
srun: cpu_bind       : default (0)
srun: mem_bind       : default (0)
srun: verbose        : 1
srun: slurmd_debug   : 0
srun: immediate      : false
srun: label output   : false
srun: unbuffered IO  : false
srun: overcommit     : false
srun: threads        : 60
srun: checkpoint_dir : /var/slurm/checkpoint
srun: wait           : 0
srun: nice           : -2
srun: account        : (null)
srun: comment        : (null)
srun: dependency     : (null)
srun: exclusive      : false
srun: bcast          : false
srun: qos            : (null)
srun: constraints    : mincpus-per-node=1 mem-per-cpu=1024M
srun: geometry       : (null)
srun: reboot         : yes
srun: rotate         : no
srun: preserve_env   : false
srun: network        : (null)
srun: propagate      : NONE
srun: prolog         : (null)
srun: epilog         : (null)
srun: mail_type      : NONE
srun: mail_user      : (null)
srun: task_prolog    : (null)
srun: task_epilog    : (null)
srun: multi_prog     : no
srun: sockets-per-node  : -2
srun: cores-per-socket  : -2
srun: threads-per-core  : -2
srun: ntasks-per-node   : -2
srun: ntasks-per-socket : -2
srun: ntasks-per-core   : -2
srun: plane_size        : 4294967294
srun: core-spec         : NA
srun: power             :
srun: remote command    : `python -m mpi4py global_flexible.py -n 8 4 -b bohrium'
srun: launching 13466356.0 on host node172, 16 tasks: [0-15]
srun: launching 13466356.0 on host node173, 16 tasks: [16-31]
srun: route default plugin loaded
srun: Node node172, 16 tasks started
srun: Node node173, 16 tasks started
WARNING: Error in initializing MVAPICH2 ptmalloc library.Continuing without InfiniBand registration cache support.
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.708 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:47.713 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset ETOPO5_Ice_g_gmt4.nc ...
2019-05-28 16:26:48.468 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset forcing_1deg_global_interpolated.nc ...
2019-05-28 16:26:48.496 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset forcing_1deg_global_interpolated.nc ...
2019-05-28 16:26:48.583 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset forcing_1deg_global_interpolated.nc ...
2019-05-28 16:26:48.595 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset forcing_1deg_global_interpolated.nc ...
2019-05-28 16:26:48.606 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset forcing_1deg_global_interpolated.nc ...
2019-05-28 16:26:48.611 | INFO     | veros.tools.assets:get_asset:73 - Downloading asset forcing_1deg_global_interpolated.nc ...
Traceback (most recent call last):
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/groups/ocean/software/mpi4py_mvapich231/gcc/3.0.1/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/groups/ocean/software/mpi4py_mvapich231/gcc/3.0.1/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/groups/ocean/software/mpi4py_mvapich231/gcc/3.0.1/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "global_flexible.py", line 16, in <module>
    DATA_FILES = veros.tools.get_assets('global_flexible', os.path.join(BASE_PATH, 'assets.yml'))
  File "/lustre/hpc/ocean/software/veros/repo23052019/veros/tools/assets.py", line 81, in get_assets
    return {key: get_asset(val['url'], val.get('md5', None)) for key, val in assets.items()}
  File "/lustre/hpc/ocean/software/veros/repo23052019/veros/tools/assets.py", line 81, in <dictcomp>
    return {key: get_asset(val['url'], val.get('md5', None)) for key, val in assets.items()}
  File "/lustre/hpc/ocean/software/veros/repo23052019/veros/tools/assets.py", line 77, in get_asset
    raise AssetError('Mismatching MD5 checksum on asset %s' % target_filename)
veros.tools.assets.AssetError: Mismatching MD5 checksum on asset forcing_1deg_global_interpolated.nc
srun: Complete job step 13466356.0 received
slurmstepd: error: *** STEP 13466356.0 ON node172 CANCELLED AT 2019-05-28T16:26:49 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Complete job step 13466356.0 received
srun: Received task exit notification for 16 tasks (status=0x0009).
srun: error: node172: tasks 0-15: Killed
srun: Terminating job step 13466356.0
srun: Complete job step 13466356.0 received
srun: Received task exit notification for 16 tasks (status=0x0009).
srun: error: node173: tasks 16-31: Killed
```

**Comment by dionhaefner** [comment] 2019-05-31 11:07
That's because every process you spawn tries to download the asset at the same time, and they override each others progress on disk. Run the setup once without MPI (to pre-download the assets) to work around this.

This could be circumvented by using some locking mechanism in the future.

**Comment by nutrik** [comment] 2019-05-31 13:10
Thanks, that solved my problem! But another one just popped up. 
It seems interpolation routine doesn't work for bathymetry and I don't know why it cannot interpolate 
global data in MPI's subdomains. It must be straitforward given that global data are available on each MPI process.

**Veros log:**

```
Setting up everything
Traceback (most recent call last):
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/groups/ocean/software/mpi4py_mvapich231/gcc/3.0.1/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/groups/ocean/software/mpi4py_mvapich231/gcc/3.0.1/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/groups/ocean/software/mpi4py_mvapich231/gcc/3.0.1/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "global_flexible.py", line 389, in <module>
    run()
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/groups/ocean/software/python/gcc/3.6.7/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/lustre/hpc/ocean/software/veros/repo23052019/veros/tools/cli.py", line 89, in wrapped
    run(*args, **kwargs)
  File "global_flexible.py", line 384, in run
    simulation.setup()
  File "/lustre/hpc/ocean/software/veros/repo23052019/veros/veros.py", line 196, in setup
    self.set_topography(vs)
  File "/lustre/hpc/ocean/software/veros/repo23052019/veros/decorators.py", line 119, in veros_method_wrapper
    res = function(*newargs, **kwargs)
  File "global_flexible.py", line 180, in set_topography
    (topo_x_shifted, topo_y), topo_z_shifted, coords, kind='nearest', fill=False
ValueError: could not broadcast input array from shape (360,160) into shape (90,40)
srun: Complete job step 13539345.0 received
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 13539345.0 ON node172 CANCELLED AT 2019-05-31T14:34:04 ***
srun: Complete job step 13539345.0 received
srun: Received task exit notification for 16 tasks (status=0x0009).
srun: error: node172: tasks 0-15: Killed
srun: Terminating job step 13539345.0

```

**Comment by dionhaefner** [comment] 2019-05-31 13:33
Confirmed and fixed on master!

**Comment by nutrik** [comment] 2019-05-31 13:40
Thanks, it works like a charm!

**Closed** 2019-06-04 07:37 UTC
